version: "3"

services:
  web:
    build: ./web
    volumes:
      - ./web:/usr/src/app
    ports:
      - "3000:3000"
    command: bash -c "yarn && yarn start"
    links:
      - api_server

  api_server:
    build: ./api_server
    ports: 
      - "3001:3001"
    volumes:
      - ./api_server:/usr/src/app
    links:
      - db
    environment:
      ROCKET_DATABASES: "{ dashboard = { url = \"mysql://dashboard_server:5d3Sj5jHAhA3VUA2@db/dashboard\" } }"

    # diesel infer_schema macro gives warnings with this flag.
    #   - CARGO_INCREMENTAL=1
    command: bash -c "bash ./wait-for-it.sh db:3306 -q -- diesel setup && cargo watch -x run"

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: R73myerFh69nmYvk
      MYSQL_DATABASE: dashboard
      MYSQL_USER: dashboard_server
      MYSQL_PASSWORD: 5d3Sj5jHAhA3VUA2
